version: '3.8'

services:
  web:
    build: .
    container_name: lung-cancer-predictor
    ports:
      - "5000:5000"
    volumes:
      - ../models:/app/models:ro
      - ../results:/app/results:ro
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

